log_level='info'

[event_queue]
  # Use '0.0.0.0' to bind to all IPv4, '::' to bind to all IPv6 and IPv4
  healthcheck_iface = '127.0.0.1'
  healthcheck_port = 3001

  datadir = 'data'
  secretkey_path = 'data/secret.key'

[ethereum]
  # Example
  http_endpoint = "https://ropsten.infura.io/v3/API_TOKEN"
  #
  confirmations = 6

  [ethereum.erc20_bridge]
    start_height = 10817792
    address = "0x898b9F9f9Cab971d9Ceb809F93799109Abbe2D10"

  [ethereum.staking]
    start_height = 10824755
    addresses = ["0xfc9Ad8fE9E0b168999Ee7547797BC39D55d607AA", "0xfc9Ad8fE9E0b168999Ee7547797BC39D55d607AA"]

[vega]
  # Example
  grpc_endpoint = "127.0.0.1:3002"
